name: Tests

on:
  push

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Chrome
      run: sudo apt-get install google-chrome-stable
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run all tests
      run: pytest --alluredir=allure_results
    - name: save allure results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path:
          allure_results
        retention-days: 1

  make-report:
    runs-on: ubuntu-latest
    needs: tests
    name: Make allure reports
    steps:
      - uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - run: sudo dpkg -i allure_2.30.0-1_all.deb
      - name: download artefacts
        uses: actions/download-artifact@v4
      - run: allure generate -c allure-results -o _site
      - name: save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path:
            _site
          retention-days: 1


  publish-report:
    runs-on: ubuntu-latest
    needs: make-report
    name: Publication report
    steps:
      - name: download artefacts
        uses: actions/download-artifact@v4
      - name: upload artifact pages
        uses: actions/upload-pages-artifact@v3
      - name: deploy pages
        id: deployment
        uses: actions/deploy-pages@v4
